--------------------------------------------------------
--  DDL for Table AUXEVENTARCHIVE_ARC
--------------------------------------------------------

  CREATE TABLE "DISPATCHER"."AUXEVENTARCHIVE_ARC" 
   (	"EVENTCOUNTER" NUMBER(10,0), 
	"AUXID" VARCHAR2(12 BYTE), 
	"TIME" DATE, 
	"GMTTIME" DATE, 
	"X" NUMBER(17,7), 
	"Y" NUMBER(17,7), 
	"FUEL" NUMBER(5,0), 
	"SPEED" NUMBER(7,3), 
	"INCLINATION" NUMBER(5,2), 
	"SENSORS" NUMBER(5,0), 
	"SYSTEMTIME" DATE, 
	"EVENTTYPE" NUMBER(3,0), 
	"DST" NUMBER(17,12), 
	"MOTOHOURS" NUMBER(36,10), 
	"ODOMETER" NUMBER(15,3)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "UGH" ;
--------------------------------------------------------
--  DDL for Table AUXSTOPPAGES_ARC
--------------------------------------------------------

  CREATE TABLE "DISPATCHER"."AUXSTOPPAGES_ARC" 
   (	"STOPCOUNTER" NUMBER(10,0), 
	"AUXID" VARCHAR2(12 BYTE), 
	"TIMESTOP" DATE, 
	"TIMEGO" DATE, 
	"GMTTIMESTOP" DATE, 
	"GMTTIMEGO" DATE, 
	"X" NUMBER(17,7), 
	"Y" NUMBER(17,7), 
	"AVGSPEED" NUMBER(7,3)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "UGH" ;
--------------------------------------------------------
--  DDL for Table EVENTSTATEARCHIVE_ARC
--------------------------------------------------------

  CREATE TABLE "DISPATCHER"."EVENTSTATEARCHIVE_ARC" 
   (	"MESCOUNTER" NUMBER(10,0), 
	"VEHID" VARCHAR2(12 BYTE), 
	"TIME" DATE, 
	"GMTTIME" DATE, 
	"X" NUMBER(17,7), 
	"Y" NUMBER(17,7), 
	"WEIGHT" NUMBER(5,0), 
	"FUEL" NUMBER(5,0), 
	"SPEED" NUMBER(7,3), 
	"INCLINATION" NUMBER(5,2), 
	"HEALTHSTATUS" NUMBER(5,0), 
	"TIMESYSTEM" DATE, 
	"EVENTTYPE" NUMBER(3,0), 
	"VEHTYPE" VARCHAR2(12 BYTE), 
	"VEHCODE" NUMBER(9,0), 
	"MESNUMBER" NUMBER(38,0), 
	"MOTOHOURS" NUMBER(36,10), 
	"RECEIVED" DATE, 
	"LAT" NUMBER(36,18), 
	"LON" NUMBER(36,18), 
	"EVENTGROUP" NUMBER(5,0), 
	"EVENTCODE" NUMBER(5,0), 
	"ADDINFOID" NUMBER(16,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "UGH" ;
--------------------------------------------------------
--  DDL for Table IDLESTOPPAGES_ARC
--------------------------------------------------------

  CREATE TABLE "DISPATCHER"."IDLESTOPPAGES_ARC" 
   (	"STOPCOUNTER" NUMBER(10,0), 
	"VEHID" VARCHAR2(12 BYTE), 
	"TIMESTOP" DATE, 
	"TIMEGO" DATE, 
	"GMTTIMESTOP" DATE, 
	"GMTTIMEGO" DATE, 
	"GMTTIMELATESTKNOWN" DATE, 
	"TIMELATESTKNOWN" DATE, 
	"AUTOSTOPID" VARCHAR2(40 BYTE), 
	"USERSTOPID" VARCHAR2(40 BYTE), 
	"IDLESTOPTYPE" NUMBER(5,0), 
	"IDLESTOPTYPEAUTO" NUMBER(5,0), 
	"XBEGIN" NUMBER(17,7), 
	"YBEGIN" NUMBER(17,7), 
	"XEND" NUMBER(17,7), 
	"YEND" NUMBER(17,7), 
	"SHOVIDAUTO" VARCHAR2(30 BYTE), 
	"TIMELOAD" DATE, 
	"XLOAD" NUMBER(17,7), 
	"YLOAD" NUMBER(17,7), 
	"IDLESTOPTYPEUSER" NUMBER(5,0), 
	"SHIFTDATE" DATE, 
	"SHIFTNUM" NUMBER(3,0), 
	"SHOVIDUSER" VARCHAR2(30 BYTE), 
	"ENGINEWORKTIME" DATE, 
	"NOTE" VARCHAR2(100 BYTE), 
	"REPAIRPLACE" VARCHAR2(50 BYTE), 
	"MOVINGTYPE" VARCHAR2(20 BYTE), 
	"WEIGHTSTOP" NUMBER(15,1), 
	"WEIGHTGO" NUMBER(15,1), 
	"FUELSTOP" NUMBER(15,1), 
	"FUELGO" NUMBER(15,1), 
	"UNLOADIDAUTO" VARCHAR2(30 BYTE), 
	"TIMEUNLOAD" DATE, 
	"XUNLOAD" NUMBER(17,7), 
	"YUNLOAD" NUMBER(17,7), 
	"TIMEREFUELSTART" DATE, 
	"XREFUEL" NUMBER(17,7), 
	"YREFUEL" NUMBER(17,7), 
	"PLANNED" NUMBER(1,0), 
	"DRVSTOPTYPE" NUMBER(17,0), 
	"REPAIRSHEETCOUNTER" NUMBER(36,7), 
	"EQUIPMENTID" NUMBER(9,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "UGH" ;
--------------------------------------------------------
--  DDL for Table IDLESTOPPAGES_AUX_ARC
--------------------------------------------------------

  CREATE TABLE "DISPATCHER"."IDLESTOPPAGES_AUX_ARC" 
   (	"STOPCOUNTER" NUMBER(10,0), 
	"VEHID" VARCHAR2(12 BYTE), 
	"TIMESTOP" DATE, 
	"TIMEGO" DATE, 
	"GMTTIMESTOP" DATE, 
	"GMTTIMEGO" DATE, 
	"GMTTIMELATESTKNOWN" DATE, 
	"TIMELATESTKNOWN" DATE, 
	"AUTOSTOPID" VARCHAR2(40 BYTE), 
	"USERSTOPID" VARCHAR2(40 BYTE), 
	"IDLESTOPTYPE" NUMBER(5,0), 
	"IDLESTOPTYPEAUTO" NUMBER(5,0), 
	"XBEGIN" NUMBER(17,7), 
	"YBEGIN" NUMBER(17,7), 
	"XEND" NUMBER(17,7), 
	"YEND" NUMBER(17,7), 
	"SHOVIDAUTO" VARCHAR2(30 BYTE), 
	"TIMELOAD" DATE, 
	"XLOAD" NUMBER(17,7), 
	"YLOAD" NUMBER(17,7), 
	"IDLESTOPTYPEUSER" NUMBER(5,0), 
	"SHIFTDATE" DATE, 
	"SHIFTNUM" NUMBER(3,0), 
	"SHOVIDUSER" VARCHAR2(30 BYTE), 
	"ENGINEWORKTIME" DATE, 
	"NOTE" VARCHAR2(100 BYTE), 
	"REPAIRPLACE" VARCHAR2(50 BYTE), 
	"MOVINGTYPE" VARCHAR2(20 BYTE), 
	"WEIGHTSTOP" NUMBER(15,1), 
	"WEIGHTGO" NUMBER(15,1), 
	"FUELSTOP" NUMBER(15,1), 
	"FUELGO" NUMBER(15,1), 
	"UNLOADIDAUTO" VARCHAR2(30 BYTE), 
	"TIMEUNLOAD" DATE, 
	"XUNLOAD" NUMBER(17,7), 
	"YUNLOAD" NUMBER(17,7), 
	"TIMEREFUELSTART" DATE, 
	"XREFUEL" NUMBER(17,7), 
	"YREFUEL" NUMBER(17,7), 
	"PLANNED" NUMBER(1,0), 
	"DRVSTOPTYPE" NUMBER(17,0), 
	"EQUIPMENTID" NUMBER(9,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "UGH" ;
--------------------------------------------------------
--  DDL for Table IDLESTOPPAGES_SHOV_ARC
--------------------------------------------------------

  CREATE TABLE "DISPATCHER"."IDLESTOPPAGES_SHOV_ARC" 
   (	"STOPCOUNTER" NUMBER(10,0), 
	"VEHID" VARCHAR2(12 CHAR), 
	"TIMESTOP" DATE, 
	"TIMEGO" DATE, 
	"GMTTIMESTOP" DATE, 
	"GMTTIMEGO" DATE, 
	"GMTTIMELATESTKNOWN" DATE, 
	"TIMELATESTKNOWN" DATE, 
	"AUTOSTOPID" VARCHAR2(40 CHAR), 
	"USERSTOPID" VARCHAR2(40 CHAR), 
	"IDLESTOPTYPE" NUMBER(5,0), 
	"IDLESTOPTYPEAUTO" NUMBER(5,0), 
	"XBEGIN" NUMBER(17,7), 
	"YBEGIN" NUMBER(17,7), 
	"XEND" NUMBER(17,7), 
	"YEND" NUMBER(17,7), 
	"SHOVIDAUTO" VARCHAR2(30 CHAR), 
	"TIMELOAD" DATE, 
	"XLOAD" NUMBER(17,7), 
	"YLOAD" NUMBER(17,7), 
	"IDLESTOPTYPEUSER" NUMBER(5,0), 
	"SHIFTDATE" DATE, 
	"SHIFTNUM" NUMBER(3,0), 
	"SHOVIDUSER" VARCHAR2(30 CHAR), 
	"ENGINEWORKTIME" DATE, 
	"NOTE" VARCHAR2(100 CHAR), 
	"REPAIRPLACE" VARCHAR2(50 CHAR), 
	"MOVINGTYPE" VARCHAR2(20 CHAR), 
	"WEIGHTSTOP" NUMBER(15,1), 
	"WEIGHTGO" NUMBER(15,1), 
	"FUELSTOP" NUMBER(15,1), 
	"FUELGO" NUMBER(15,1), 
	"UNLOADIDAUTO" VARCHAR2(30 CHAR), 
	"TIMEUNLOAD" DATE, 
	"XUNLOAD" NUMBER(17,7), 
	"YUNLOAD" NUMBER(17,7), 
	"TIMEREFUELSTART" DATE, 
	"XREFUEL" NUMBER(17,7), 
	"YREFUEL" NUMBER(17,7), 
	"PLANNED" NUMBER(1,0), 
	"DRVSTOPTYPE" NUMBER(17,0), 
	"EQUIPMENTID" NUMBER(9,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "UGH" ;
--------------------------------------------------------
--  DDL for Table NONTECHEVENTARCHIVE_ARC
--------------------------------------------------------

  CREATE TABLE "DISPATCHER"."NONTECHEVENTARCHIVE_ARC" 
   (	"EVENTCOUNTER" NUMBER(10,0), 
	"NONTECHID" VARCHAR2(12 BYTE), 
	"TIME" DATE, 
	"GMTTIME" DATE, 
	"X" NUMBER(17,7), 
	"Y" NUMBER(17,7), 
	"FUEL" NUMBER(5,0), 
	"SPEED" NUMBER(7,3), 
	"INCLINATION" NUMBER(5,2), 
	"SENSORS" NUMBER(5,0), 
	"SYSTEMTIME" DATE, 
	"EVENTTYPE" NUMBER(3,0), 
	"MOTOHOURS" NUMBER(36,10)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "UGH" ;
--------------------------------------------------------
--  DDL for Table REFUELLERMESARCHIVE_ARC
--------------------------------------------------------

  CREATE TABLE "DISPATCHER"."REFUELLERMESARCHIVE_ARC" 
   (	"EVENTCOUNTER" NUMBER(10,0), 
	"REFUELLERID" VARCHAR2(12 BYTE), 
	"TIME" DATE, 
	"GMTTIME" DATE, 
	"X" NUMBER(17,7), 
	"Y" NUMBER(17,7), 
	"FUEL" NUMBER(5,0), 
	"SPEED" NUMBER(7,3), 
	"INCLINATION" NUMBER(5,2), 
	"SENSORS" NUMBER(5,0), 
	"SYSTEMTIME" DATE, 
	"EVENTTYPE" NUMBER(3,0), 
	"VOLUME_TANK1" NUMBER(36,10), 
	"VOLUME_TANK2" NUMBER(36,10), 
	"VOLUME_TANK3" NUMBER(36,10)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "UGH" ;
--------------------------------------------------------
--  DDL for Table SENSORARCHIVE_ARC
--------------------------------------------------------

  CREATE TABLE "DISPATCHER"."SENSORARCHIVE_ARC" 
   (	"ID" NUMBER(32,0), 
	"VEHID" VARCHAR2(64 CHAR), 
	"VEHTYPE" VARCHAR2(32 CHAR), 
	"GMTTIME" DATE, 
	"SENSORID" NUMBER(32,0), 
	"MINSENSORVALUE" NUMBER(32,0), 
	"AVGSENSORVALUE" NUMBER(32,0), 
	"MAXSENSORVALUE" NUMBER(32,0), 
	"PERIODSECONDS" NUMBER(38,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "UGH" ;
--------------------------------------------------------
--  DDL for Table SENSORSIMPLEVIOLATIONS_ARC
--------------------------------------------------------

  CREATE TABLE "DISPATCHER"."SENSORSIMPLEVIOLATIONS_ARC" 
   (	"ID" NUMBER(36,0), 
	"VEHID" VARCHAR2(64 CHAR), 
	"VEHTYPE" VARCHAR2(64 CHAR), 
	"SENSORID" NUMBER(36,0), 
	"SENSORVALUE" NUMBER(36,0), 
	"VIOLATYONTYPE" VARCHAR2(64 CHAR), 
	"ALERTMIN" NUMBER(36,0), 
	"WARNINGMIN" NUMBER(36,0), 
	"WARNINGMAX" NUMBER(36,0), 
	"ALERTMAX" NUMBER(36,0), 
	"GMTTIMEBEGIN" DATE, 
	"SIMPLECONDITIONID" NUMBER(38,0), 
	"GMTTIMEEND" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "UGH" ;
--------------------------------------------------------
--  DDL for Table SHOVEVENTSTATEARCHIVE_ARC
--------------------------------------------------------

  CREATE TABLE "DISPATCHER"."SHOVEVENTSTATEARCHIVE_ARC" 
   (	"EVENTCOUNTER" NUMBER(10,0), 
	"SHOVID" VARCHAR2(12 BYTE), 
	"EVENTTYPE" NUMBER(3,0), 
	"TIME" DATE, 
	"GMTTIME" DATE, 
	"X" NUMBER(17,7), 
	"Y" NUMBER(17,7), 
	"SYSTEMTIME" DATE, 
	"FUEL" NUMBER(20,0), 
	"BUCKETS" NUMBER(20,0), 
	"SPEED" NUMBER(3,0), 
	"MOTOHOURS" NUMBER(36,10), 
	"Z" NUMBER(17,7), 
	"GPSQUAL" NUMBER(3,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "UGH" ;
--------------------------------------------------------
--  DDL for Table SIMPLETRANSITIONS_ARC
--------------------------------------------------------

  CREATE TABLE "DISPATCHER"."SIMPLETRANSITIONS_ARC" 
   (	"TRANSCOUNTER" NUMBER(10,0), 
	"VEHID" VARCHAR2(12 BYTE), 
	"TIMEGO" DATE, 
	"GMTTIMEGO" DATE, 
	"XGO" NUMBER(17,7), 
	"YGO" NUMBER(17,7), 
	"FUELGO" NUMBER(15,2), 
	"TIMESTOP" DATE, 
	"GMTTIMESTOP" DATE, 
	"XSTOP" NUMBER(17,7), 
	"YSTOP" NUMBER(17,7), 
	"WEIGHT" NUMBER(15,1), 
	"FUELSTOP" NUMBER(15,2), 
	"MAXSPEED" NUMBER(7,3), 
	"INTEGRALINCLINE" NUMBER(10,0), 
	"MOVELENGTH" NUMBER(15,3), 
	"MOVEHEIGHT" NUMBER(15,2), 
	"MAXINCLINE" NUMBER(10,0), 
	"AVGSPEED" NUMBER(36,3), 
	"VEHCODE" NUMBER(9,0), 
	"SYSTEMTIME" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "UGH" ;
--------------------------------------------------------
--  DDL for Table TIREPRESSUREARCHIVE_ARC
--------------------------------------------------------

  CREATE TABLE "DISPATCHER"."TIREPRESSUREARCHIVE_ARC" 
   (	"EVENTCOUNTER" NUMBER(10,0), 
	"VEHID" VARCHAR2(12 BYTE), 
	"TIME" DATE, 
	"GMTTIME" DATE, 
	"X" NUMBER(17,7), 
	"Y" NUMBER(17,7), 
	"PRESSURE1" NUMBER(17,7), 
	"PRESSURE2" NUMBER(17,7), 
	"PRESSURE3" NUMBER(17,7), 
	"PRESSURE4" NUMBER(17,7), 
	"PRESSURE5" NUMBER(17,7), 
	"PRESSURE6" NUMBER(17,7), 
	"PRESSURE7" NUMBER(17,7), 
	"PRESSURE8" NUMBER(17,7), 
	"PRESSURE9" NUMBER(17,7), 
	"PRESSURE10" NUMBER(17,7), 
	"PRESSURE11" NUMBER(17,7), 
	"PRESSURE12" NUMBER(17,7), 
	"TEMPERATURE1" NUMBER, 
	"TEMPERATURE2" NUMBER, 
	"TEMPERATURE3" NUMBER, 
	"TEMPERATURE4" NUMBER, 
	"TEMPERATURE5" NUMBER, 
	"TEMPERATURE6" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "UGH" ;
--------------------------------------------------------
--  DDL for Table TIREPRESSUREERRORSARCHIVE_ARC
--------------------------------------------------------

  CREATE TABLE "DISPATCHER"."TIREPRESSUREERRORSARCHIVE_ARC" 
   (	"EVENTCOUNTER" NUMBER(10,0), 
	"VEHID" VARCHAR2(12 BYTE), 
	"TIME" DATE, 
	"GMTTIME" DATE, 
	"X" NUMBER(17,7), 
	"Y" NUMBER(17,7), 
	"TIRELOCATION" NUMBER(3,0), 
	"PRESSURE" NUMBER(17,7), 
	"STATUS" NUMBER(3,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "UGH" ;
--------------------------------------------------------
--  DDL for Table TRACKEREVENTARCHIVE_ARC
--------------------------------------------------------

  CREATE TABLE "DISPATCHER"."TRACKEREVENTARCHIVE_ARC" 
   (	"TRACKEREVENTARCHIVEID" NUMBER(38,0), 
	"TRACKERID" VARCHAR2(256 CHAR), 
	"GMTTIME" DATE, 
	"SYSTEMTIME" DATE, 
	"X" NUMBER(20,10), 
	"Y" NUMBER(20,10), 
	"SPEED" NUMBER(10,2), 
	"HEALTHSTATUS" NUMBER(5,0), 
	"EVENTTYPEID" NUMBER(38,0), 
	"EVENTDESCRIPTION" VARCHAR2(200 BYTE), 
	"ENTERPRISEID" NUMBER(38,0), 
	"LAT" NUMBER(20,10), 
	"LON" NUMBER(20,10), 
	"PERSONNELID" NUMBER(36,0), 
	"TIME" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "UGH" ;

   COMMENT ON COLUMN "DISPATCHER"."TRACKEREVENTARCHIVE_ARC"."TRACKEREVENTARCHIVEID" IS '';
   COMMENT ON COLUMN "DISPATCHER"."TRACKEREVENTARCHIVE_ARC"."TRACKERID" IS '';
   COMMENT ON COLUMN "DISPATCHER"."TRACKEREVENTARCHIVE_ARC"."GMTTIME" IS '';
   COMMENT ON COLUMN "DISPATCHER"."TRACKEREVENTARCHIVE_ARC"."SYSTEMTIME" IS '';
   COMMENT ON COLUMN "DISPATCHER"."TRACKEREVENTARCHIVE_ARC"."X" IS '';
   COMMENT ON COLUMN "DISPATCHER"."TRACKEREVENTARCHIVE_ARC"."Y" IS '';
   COMMENT ON COLUMN "DISPATCHER"."TRACKEREVENTARCHIVE_ARC"."SPEED" IS '';
   COMMENT ON COLUMN "DISPATCHER"."TRACKEREVENTARCHIVE_ARC"."HEALTHSTATUS" IS '';
   COMMENT ON COLUMN "DISPATCHER"."TRACKEREVENTARCHIVE_ARC"."EVENTTYPEID" IS '';
   COMMENT ON COLUMN "DISPATCHER"."TRACKEREVENTARCHIVE_ARC"."EVENTDESCRIPTION" IS '';
   COMMENT ON COLUMN "DISPATCHER"."TRACKEREVENTARCHIVE_ARC"."ENTERPRISEID" IS '';
   COMMENT ON COLUMN "DISPATCHER"."TRACKEREVENTARCHIVE_ARC"."LAT" IS '';
   COMMENT ON COLUMN "DISPATCHER"."TRACKEREVENTARCHIVE_ARC"."LON" IS '';
   COMMENT ON COLUMN "DISPATCHER"."TRACKEREVENTARCHIVE_ARC"."PERSONNELID" IS '';
   COMMENT ON COLUMN "DISPATCHER"."TRACKEREVENTARCHIVE_ARC"."TIME" IS '';
   COMMENT ON TABLE "DISPATCHER"."TRACKEREVENTARCHIVE_ARC"  IS 'архив всех сообщений персонала';
--------------------------------------------------------
--  DDL for Table TRACKERSHISTORY_ARC
--------------------------------------------------------

  CREATE TABLE "DISPATCHER"."TRACKERSHISTORY_ARC" 
   (	"TRACKERHISTORYID" NUMBER(10,0), 
	"TRACKERID" NUMBER(10,0), 
	"EVENTTIMEGMT" DATE, 
	"LONGITUDE" NUMBER(20,10), 
	"LATITUDE" NUMBER(20,10), 
	"X" NUMBER(20,10), 
	"Y" NUMBER(20,10), 
	"SPEED" NUMBER(5,2), 
	"SATELLITES" NUMBER(3,0), 
	"PERSONID" NUMBER(10,0), 
	"TRACKERKEY" VARCHAR2(100 CHAR)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "UGH" ;
--------------------------------------------------------
--  DDL for Table TRACKERSHISTORY1_ARC
--------------------------------------------------------

  CREATE TABLE "DISPATCHER"."TRACKERSHISTORY1_ARC" 
   (	"TRACKERHISTORYID" NUMBER(10,0), 
	"TRACKERID" NUMBER(10,0), 
	"EVENTTIMEGMT" DATE, 
	"LONGITUDE" NUMBER(20,10), 
	"LATITUDE" NUMBER(20,10), 
	"X" NUMBER(20,10), 
	"Y" NUMBER(20,10), 
	"SPEED" NUMBER(5,2), 
	"SATELLITES" NUMBER(3,0), 
	"PERSONID" NUMBER(10,0), 
	"TRACKERKEY" VARCHAR2(100 CHAR)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "UGH" ;
--------------------------------------------------------
--  Constraints for Table IDLESTOPPAGES_ARC
--------------------------------------------------------

  ALTER TABLE "DISPATCHER"."IDLESTOPPAGES_ARC" MODIFY ("PLANNED" NOT NULL ENABLE);
  ALTER TABLE "DISPATCHER"."IDLESTOPPAGES_ARC" MODIFY ("GMTTIMESTOP" NOT NULL ENABLE);
  ALTER TABLE "DISPATCHER"."IDLESTOPPAGES_ARC" MODIFY ("TIMESTOP" NOT NULL ENABLE);
  ALTER TABLE "DISPATCHER"."IDLESTOPPAGES_ARC" MODIFY ("VEHID" NOT NULL ENABLE);
  ALTER TABLE "DISPATCHER"."IDLESTOPPAGES_ARC" MODIFY ("STOPCOUNTER" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table IDLESTOPPAGES_AUX_ARC
--------------------------------------------------------

  ALTER TABLE "DISPATCHER"."IDLESTOPPAGES_AUX_ARC" MODIFY ("PLANNED" NOT NULL ENABLE);
  ALTER TABLE "DISPATCHER"."IDLESTOPPAGES_AUX_ARC" MODIFY ("GMTTIMESTOP" NOT NULL ENABLE);
  ALTER TABLE "DISPATCHER"."IDLESTOPPAGES_AUX_ARC" MODIFY ("TIMESTOP" NOT NULL ENABLE);
  ALTER TABLE "DISPATCHER"."IDLESTOPPAGES_AUX_ARC" MODIFY ("VEHID" NOT NULL ENABLE);
  ALTER TABLE "DISPATCHER"."IDLESTOPPAGES_AUX_ARC" MODIFY ("STOPCOUNTER" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table IDLESTOPPAGES_SHOV_ARC
--------------------------------------------------------

  ALTER TABLE "DISPATCHER"."IDLESTOPPAGES_SHOV_ARC" MODIFY ("PLANNED" NOT NULL ENABLE);
  ALTER TABLE "DISPATCHER"."IDLESTOPPAGES_SHOV_ARC" MODIFY ("GMTTIMESTOP" NOT NULL ENABLE);
  ALTER TABLE "DISPATCHER"."IDLESTOPPAGES_SHOV_ARC" MODIFY ("TIMESTOP" NOT NULL ENABLE);
  ALTER TABLE "DISPATCHER"."IDLESTOPPAGES_SHOV_ARC" MODIFY ("VEHID" NOT NULL ENABLE);
  ALTER TABLE "DISPATCHER"."IDLESTOPPAGES_SHOV_ARC" MODIFY ("STOPCOUNTER" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table REFUELLERMESARCHIVE_ARC
--------------------------------------------------------

  ALTER TABLE "DISPATCHER"."REFUELLERMESARCHIVE_ARC" MODIFY ("EVENTCOUNTER" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SENSORARCHIVE_ARC
--------------------------------------------------------

  ALTER TABLE "DISPATCHER"."SENSORARCHIVE_ARC" MODIFY ("SENSORID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SENSORSIMPLEVIOLATIONS_ARC
--------------------------------------------------------

  ALTER TABLE "DISPATCHER"."SENSORSIMPLEVIOLATIONS_ARC" MODIFY ("GMTTIMEEND" NOT NULL ENABLE);
  ALTER TABLE "DISPATCHER"."SENSORSIMPLEVIOLATIONS_ARC" MODIFY ("GMTTIMEBEGIN" NOT NULL ENABLE);
  ALTER TABLE "DISPATCHER"."SENSORSIMPLEVIOLATIONS_ARC" MODIFY ("SENSORID" NOT NULL ENABLE);
  ALTER TABLE "DISPATCHER"."SENSORSIMPLEVIOLATIONS_ARC" MODIFY ("VEHTYPE" NOT NULL ENABLE);
  ALTER TABLE "DISPATCHER"."SENSORSIMPLEVIOLATIONS_ARC" MODIFY ("VEHID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SIMPLETRANSITIONS_ARC
--------------------------------------------------------

  ALTER TABLE "DISPATCHER"."SIMPLETRANSITIONS_ARC" MODIFY ("TRANSCOUNTER" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRACKEREVENTARCHIVE_ARC
--------------------------------------------------------

  ALTER TABLE "DISPATCHER"."TRACKEREVENTARCHIVE_ARC" MODIFY ("TRACKEREVENTARCHIVEID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRACKERSHISTORY_ARC
--------------------------------------------------------

  ALTER TABLE "DISPATCHER"."TRACKERSHISTORY_ARC" MODIFY ("TRACKERHISTORYID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRACKERSHISTORY1_ARC
--------------------------------------------------------

  ALTER TABLE "DISPATCHER"."TRACKERSHISTORY1_ARC" MODIFY ("TRACKERHISTORYID" NOT NULL ENABLE);
